version: "2"
checks:
  similar-code:
    enabled: true
    config:
      languages:
      - javascript
  duplication:
    enabled: true
    config:
      languages:
      - javascript
exclude_patterns:
- "src/config"
- "src/test"
- "src/app/Validators"
- "src/node_modules"
- "src/database"