version: "2"
checks:
  similar-code:
    enabled: true
    config:
      languages:
      - javascript
  duplication:
    enabled: false
    config:
      languages:
      - javascript
exclude_patterns:
- "src/config"
- "src/test"
- "src/node_modules"
- "src/database"
- "src/utils/Wheres.js"