version: '3'
services:
  adonis-mysql:
    image: mysql
    container_name: "${APP_NAME}_MYSQL"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - $PWD/data:/var/lib/mysql
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - adonis-network

  adonis-app:
    build:
      context: .
      dockerfile: docker/dockerfile
    restart: always
    container_name: "${APP_NAME}_APP"
    env_file:
      - src/.env
    environment:
      DB_HOST: adonis-mysql
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - adonis-mysql
    networks:
      - adonis-network
  
networks:
  adonis-network:
